augmented-pandemic/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
	url(r'^game/', include('game.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/game'
    )),
    url(r'^', include('django.contrib.auth.urls')),    
]

game/urls.py
"""Mapping URLs to views"""

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = 'game'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^users/$', views.users, name='users'),
    url(r'^user_detail/(?P<user_id>\w+)$', views.user_detail, name='user_detail'),
    url(r'^leaderboard/$', views.leaderboard, name='leaderboard'),
    url(r'^play/$', views.play, name='play'),
    url(r'^database/location_json/$', views.location_json, name='location_json'),
    url(r'^database/safezone_json/$', views.safezone_json, name='safezone_json'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^(?P<location_name>.+)/win/$', views.win, name='win'),
    url(r'^(?P<location_name>.+)/lose/$', views.lose, name='lose'),
]

game/models.py
"""Game app models"""

from django.db import models
from django.contrib.auth.models import User
#from django.db.models.signals import post_save
#from django.dispatch import receiver

class Location(models.Model):
    """Regions of infection"""
    location_text = models.CharField(max_length=200)
    # infection_rate = models.IntegerField(default=30)
    matches_lost = models.IntegerField(default=30)
    matches_won = models.IntegerField(default=70)

    def total_matches(self):
        """Returns total matches played in region"""
        won = self.matches_won
        lost = self.matches_lost
        return float(won + lost)

    def infection_rate(self):
        """Returns infection rate of location"""
        rate = (self.matches_lost / self.total_matches())*100
        return rate

    def __str__(self):
        """Returns location name"""
        return self.location_text

class Safezone(models.Model):
    """Regions of infection"""
    location_text = models.CharField(max_length=200)
    antidotes_given_out = models.IntegerField(default=0)

    def __str__(self):
        """Returns location name"""
        return self.location_text

class Profile(models.Model):
    """User Profile model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    matches_won = models.IntegerField(default=0)
    matches_lost = models.IntegerField(default=0)
    num_antidotes = models.IntegerField(default=0)
    # total_matches = models.IntegerField(default=0)
    def total_matches(self):
        # Returns total matches played
        won = self.matches_won
        lost = self.matches_lost
        return float(won + lost)

    def success_rate(self):
        # Returns matches won out of total matches
        success = (self.matches_won / self.total_matches())*100
        return success

game/views.py
"""Game views"""
import json
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core import serializers
from .models import Location
from .models import Safezone

def index(request):
    """Homepage view"""
    context = {'text': 'Welcome to our game'}
    return render(request, 'game/index.html', context)

# This isn't used right now
# def register(request):
#     context = {'text': 'Register here'}
#     return render(request, 'registration/register.html', context)

def users(request):
    """User list view"""
    context = {'text': 'User list here'}
    return render(request, 'game/users.html', context)

def user_detail(request, user_id):
    """User profile view"""
    return HttpResponse("This page will have user details")

def leaderboard(request):
    """Leaderboard view"""
    context = {'text': 'Leaderboard goes here'}
    return render(request, 'game/leaderboard.html', context)

def play(request):
    """Game view"""
    # context = {'text': 'Leaderboard goes here'}
    return render(request, 'game/play.html')

def location_json(request):
    """Retrieving location information"""
    location_list = Location.objects.all()
    location_json = serializers.serialize('json', location_list)
    # Convert JSON to python dict
    location_object = json.loads(location_json)

    # Create a new object and make the keys be the location names so it's easier to search later
    output_object = {}
    for location in location_object:
        location_text = location['fields']['location_text']
        output_object[location_text] = location
    return HttpResponse(json.dumps(output_object), content_type='application/javascript')

def safezone_json(request):
    """Retrieving safezone locations"""
    safezone_list = Safezone.objects.all()
    safezoneJSON = serializers.serialize('json', safezone_list)
    # Convert JSON to python dict
    safezoneObject = json.loads(safezoneJSON)

    # Create a new object and make the keys be the location names so it's easier to search later
    outputObject = {}
    for location in safezoneObject:
        location_text = location['fields']['location_text']
        outputObject[location_text] = location
    return HttpResponse(json.dumps(outputObject), content_type='application/javascript')

def win(request, location_name):
    """Saving matches won to database"""
    location = get_object_or_404(Location, location_text=location_name)
    location.matches_won += 1
    location.save()
    return HttpResponse("matches_won increased by 1")

def lose(request, location_name):
    """Saving matches lost to database"""
    location = get_object_or_404(Location, location_text=location_name)
    location.matches_lost += 1
    location.save()
    return HttpResponse("matches_lost increased by 1")

game/templates/game/index.html
<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
		<title>Augmented Pandemic Home Page</title>
		{% load static %}
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'game/css/index.css' %}" />
		<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Cousine|Monda" rel="stylesheet">
	</head>
	<body>
		<div id="navbar">{% include "game/navigation_bar.html" %}</div>
		<div class="text">
			<p>{{ text }}</p>
		</div>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</body>
</html>

game/templates/game/leaderboard.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>Leaderboard</title>
        {% load static %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Cousine|Monda" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/leaderboard.css' %}" />
    </head>
    <body>
        {% include "game/navigation_bar.html" %}
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

game/templates/game/leaderboardry.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>


h1 {text-align:center;
}
table {
    width:100%;
}
table, th, td {
    border: 1px solid red;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}

</style>
</head>
<body>
<h1> Augmented Leaders </h1>
<table>
  <tr>
    <th>USERNAME</th>
    <th>CURE RATE</th>
  </tr>
  <tr>
    <td>Jordon</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Smith</td>
    <td>750</td>
  </tr>
  <tr>
    <td>Josh</td>
    <td>500</td>
  </tr>
</table>
<br>

</body>
</html>

game/templates/game/login_backup.html
<form action="action_page.php">
	<div class="container">
		<label><b>Username</b></label>
		<input type="text" placeholder="Enter Username" name="uname" required><br>
		<label><b>Password</b></label>
		<input type="password" placeholder="Enter Password" name="psw" required><br>
		<input type="checkbox" checked="checked"> Remember me<br>
		<button type="submit">Login</button>
		<button type="button" class="cancelbtn">Cancel</button><br>
		<span class="psw">Forgot <a href="#">password?</a></span>
		<span class="psw"><a href="{% url 'game:register' %}">New user?</a></span>
	</div>
</form>

game/templates/game/navigation_bar.html
<!-- Bootstrap Navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle grouped for better mobile display -->
    <div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'game:play' %}">Fight the Infection</a>
    </div>

    <!-- Group links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
				<li><a href="{% url 'game:index' %}">Home</a></li>
				<li><a href="{% url 'game:users' %}">Users</a></li>
				<li><a href="{% url 'game:leaderboard' %}">Leaderboard</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
				<li><a href="/register">Register</a></li>
				<li><a href="/login">Login</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

game/templates/game/play.html
<!DOCTYPE html>
<html>
	<head>
		<title>Fight the Infection!</title>
		<meta name="viewport" content="initial-scale=1.0">
		<meta charset="utf-8">
		
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Cousine|Monda" rel="stylesheet">
		{% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/play.css' %}" />
	</head>
	<body>
		<div id="navigationBar">{% include "game/navigation_bar.html" %}</div>
		<div id="textArea">
            <h1 id="gameTitle">Fight the Infection</h1>
			<div id="leftSide">
				<p class="titles">
					Current Location: <span class="info" id="location"></span>
				</p>
				<br>
				<p class="titles" id="GlobalInfectionRate">
					Global Infection Rate: <span class="info" id="global"></span>
				</p>
				<p class="titles" id="LocalInfectionRate">
					Local Infection Rate: <span class="info" id="local"></span>
				</p>
				<p class="titles" id="numAntidotesText">Number of antidotes: 0</p>
				<div class="buttons" id="userSelection">
					{% csrf_token %}
					<button id="rockButton" class="RPSButton">Quarantine</button>
					<button id="paperButton" class="RPSButton">Cure</button>
					<button id="scissorsButton" class="RPSButton">Rescue</button>
				</div><br>
				<div class="buttons" id="generalButtons">
					<input id="checkLocationButton" type="button" value="Check Location">
					<input id="centerMapButton" type="button" value="Center Map">
					<input id="toggleMapButton" type="button" value="Toggle Map">
				</div>
			</div>
            <div id="rightSide">
                <div id="infoWindow"><p>Information Window</p></div>
            </div>
		</div>
		<div id="map"></div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7lpJkNjlPd3Cl6UJAr7nAyM1U0eMTH6I&callback=initMap"></script>
		<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
		<script src="{% static 'game/js/play.js' %}"></script>
		<script src="{% static 'game/js/rockpaperscissor.js' %}"></script>
	</body>
</html>

game/templates/game/register_backup.html
<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
		<title>User Registration Page</title>
	</head>
	<body>
		{% include "game/navigation_bar.html" %}
		<p>{{ text }}</p>
    <form action="action_page.php">

      <div class="container">
        <label><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required><br>
        <label><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required><br>
        <label><b>Confirm Password</b></label>
        <input type="password" placeholder="Retype Password" name="psw" required>
        <br><br>
        <button type="submit">Submit</button>
      </div>
    </form>
	</body>
</html>

game/templates/game/users.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>User List</title>
        {% load static %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Cousine|Monda" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/users.css' %}" />
    </head>
    <body>
        {% include "game/navigation_bar.html" %}
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>